dataset:
  name: 'tofdc'
  root_dir: '/home/lasinac/ticDSO/Implementacion paper 9/DCDepth/TOFDC'
  train_list: '/home/lasinac/ticDSO/Implementacion paper 9/DCDepth/TOFDC/TOFDC_train.txt'
  test_list: '/home/lasinac/ticDSO/Implementacion paper 9/DCDepth/TOFDC/TOFDC_test.txt'
  input_height: 384
  input_width: 512
  min_depth: 0.1
  max_depth: 5.0

model:
  type: 'DCTProg'
  output_space: 'metric'
  encoder: 'tiny12'  # Swin Transformer versi√≥n tiny con window_size=12
  pretrain: null  # O especifica una ruta si tienes un modelo preentrenado
  ape: false
  drop_path_rate: 0.2
  drop_path_rate_crf: 0.0
  seq_dropout_rate: 0.0
  downsample_strategy: 'dct'

evaluation:
  do_kb_crop: false
  garg_crop: false
  eigen_crop: false

training:
  work_dir: './outputs/tofdc'
  log_freq: 100

loss:
  variance_focus: 0.85
  min_valid_pixels: 4
  square_root: true
  beta: 1.0
  freq_reg_weight: 0.1
  smooth_reg_weight: 0.1

optimization:
  max_lr: 0.001
  lr_ratio: 10.0
  weight_decay: 0.01
  div_factor: 25.0
  final_div_factor: 10000.0
  pct_start: 0.3
  anneal_strategy: 'cos'